# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roundtrip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roundtrip
  template:
    metadata:
      labels:
        app: roundtrip
    spec:
      containers:
      - name: roundtrip
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/$GCLOUD_PROJECT/roundtrip:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"